comment:
  layout: header, changes, diff
coverage:
  notify:
    slack:
      default:
        url: secret:8dESiEjdqyDXpd094u5kgD4vRvHLCOPjJAclrG6DVSMC+y8goM1p6UhNHJvYyB+iVAjwvoGZACna+lq+Vm08asxc2mwm5Ina5GlLuDYLTijU07/nqwPUuTUqYLOn6envODqB0vKuM73dEwtGI/M1dXbCHhWI6uzMsev0m/xUJUo=
        branches:
        - master
        - develop
        - feature/*
        threshold: "0.5%"
        attachments: "sunburst, diff"
    gitter:
      default:
        branches:
        - master
        - develop
        - feature/*
        threshold: "0.5%"
        url: secret:T/bOzFjYiR1f5G/sUgcN6CySceNwkzOBG6pq4sm+oynvz4js/KUQPGo56QNFrwDHhcZ1Uw3iob1svc5w1IeIcuAuolv455MXaMxgJQiqiMj5mj5VzUaOw/rdDP6JyAp5
  status:
    patch: false