coverage:
  precision: 2
  round: down
  range: "50...70"

  status:
    project:
      default:
        target: auto
        if_no_uploads: error

    patch:
      default:
        if_no_uploads: error

    changes: true

  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        branches:
          - *
        threshold: "0.5%"
        attachments: "sunburst, diff" # list of attachments to include in notification
        message: "template string"    # [advanced] -> see "customized message" below

comment:
  layout: "header, diff, changes, suggestions"
  behavior: default